

const ThoughtOfTheDay = () => {

  const thoughts = [
  "Every day is a new chance to grow.",
  "Small steps lead to big changes.",
  "Kindness costs nothing but means everything.",
  "Believe in yourself a little more today.",
  "Learning never goes to waste.",
  "Your effort matters, even when progress feels slow.",
  "Mistakes are proof that you are trying.",
  "Stay curious and keep asking questions.",
  "Patience makes difficult things easier.",
  "Be proud of how far you have come.",
  "A positive mindset changes everything.",
  "Focus on progress, not perfection.",
  "Your attitude shapes your day.",
  "Hard work beats talent when talent doesn’t work hard.",
  "Do one good thing today.",
  "Challenges help you discover your strength.",
  "Consistency creates success.",
  "You learn more by trying than by waiting.",
  "Confidence grows with practice.",
  "Every effort counts.",
  "Choose growth over comfort.",
  "Listening is as important as speaking.",
  "Your future is built by today’s actions.",
  "Stay humble and keep learning.",
  "Time used wisely is time well spent.",
  "Believe you can improve, and you will.",
  "Helping others helps you too.",
  "Dream big, start small.",
  "Your mindset can turn obstacles into opportunities.",
  "Discipline today brings freedom tomorrow.",
  "Success begins with showing up.",
  "Focus on what you can control.",
  "Your thoughts shape your actions.",
  "Be brave enough to try again.",
  "Learning is a lifelong journey.",
  "Effort creates opportunity.",
  "Take responsibility for your growth.",
  "Stay focused on your goals.",
  "Hard days build strong people.",
  "Practice makes progress.",
  "You are capable of more than you think.",
  "A calm mind makes better decisions.",
  "Failure is feedback, not defeat.",
  "Growth happens outside your comfort zone.",
  "Your habits define your future.",
  "One step forward is still progress.",
  "Believe in steady improvement.",
  "Gratitude improves your perspective.",
  "Success is built one day at a time.",
  "Be patient with yourself.",
  "Curiosity leads to discovery.",
  "Effort today brings results tomorrow.",
  "Your mindset matters more than luck.",
  "Do your best and learn from the rest.",
  "Challenges make achievements meaningful.",
  "Confidence comes from preparation.",
  "Stay consistent, even when it’s hard.",
  "Your actions create your identity.",
  "Learning from mistakes builds wisdom.",
  "Be open to new ideas.",
  "Small improvements add up.",
  "Focus on solutions, not problems.",
  "Your goals deserve commitment.",
  "Self-belief fuels success.",
  "Hard work creates self-respect.",
  "Growth requires patience.",
  "Your effort inspires others.",
  "Every challenge is a lesson.",
  "Stay disciplined and determined.",
  "Success favors persistence.",
  "Choose progress over excuses.",
  "Learning starts with curiosity.",
  "Your mindset shapes your future.",
  "Stay focused and keep improving.",
  "Good habits create good outcomes.",
  "Confidence grows through action.",
  "Your journey is unique.",
  "Progress is better than perfection.",
  "Every day is a chance to learn.",
  "Be consistent with your effort.",
  "Success starts with self-belief.",
  "Your potential grows with effort.",
  "Keep going, even when it’s tough.",
  "Discipline builds long-term success.",
  "Learning makes you stronger.",
  "Your choices define your path.",
  "Stay motivated by your goals.",
  "Every step forward matters.",
  "Believe in steady growth.",
  "Your future depends on today.",
  "End today knowing you tried."
]


  const idx = Math.floor(Math.random() * 91);

return (
  <div className="thought">
    {thoughts[idx]}
  </div>
);

}

export default ThoughtOfTheDay